### ISSUE TITLE
Add basic C programs 

### ISSUE THREAD

**Issue by Akanksha1212** [Akanksha1212/C_Programs#5]

**Comment by pb-10** [comment]
Hey @Akanksha1212,

I came across your repo as I was looking for some good repos to contribute for HacktoberFest and I saw that you had an issue in which I would like to contribute!

So, I was just wondering that if I do contribute to your repo, then what basic C programs should I add? I was thinking about some programs on:
1) Array
2)  Loops, 
3) Fibonacci series 
4) Prime number.
5) Palindrome number.
6) Factorial.
7) Armstrong number.
8) Sum of Digits.
9) Reverse Number.
10) Swap two numbers without using third variable.

**Comment by Akanksha1212** [comment]
Hi @pb-10 
If the program that you want to add is not already in the repo and open PRs then feel free to contribute.

**Comment by pb-10** [comment]
okay, thanks!

**Comment by Arccfire** [comment]
hello 
i would like to contribute .

**Comment by palashitb** [comment]
hey
I have a palindrome code that can work for nos. and letters all the same. I want to contribute

**Comment by bhavya1108** [comment]
hey
i saw your fibonacci no code,i think there can be better code for it which can calculate value for large value of n.i will like to contribute

**Comment by Akanksha1212** [comment]
Hi @bhavya1108 
Pls make a PR for your Fibonacci code by updating the old one currently present in the repo.

**Comment by Axhat** [comment]
i have some of basic  programmes based on arrays exclusively for beginners .

**Comment by Ad-S** [comment]
I have contributed codes on printing pascals triangle and finding proodut using russian peasent algorithm please have a look on them

**Comment by Strongsaxophone** [comment]
Hi @Akanksha1212,
 Can I add vector implementation to this repository? in fact I had implemented it and I want to merge it with this repository too, you can find it [here](https://github.com/Strongsaxophone/c_vector).

**Comment by LezendarySandwich** [comment]
Hi @Akanksha1212 
I would like to add selection sort in C.
